"""Add initial categories data

Revision ID: 4b54af39abdd
Revises: cc8d1f73ce0d
Create Date: 2025-08-24 20:38:43.304613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b54af39abdd'
down_revision = 'cc8d1f73ce0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    data_upgrades()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    # Delete data in downgrade
    table = sa.sql.table('categories', sa.Column('name', sa.String()))
    op.execute(table.delete().where(table.c.name.in_(['Программирование', 'Математика', 'Языкознание'])))

def data_upgrades():
    """Add any optional data upgrade migrations here!"""

    table = sa.sql.table('categories', sa.Column('name', sa.String()))

    op.bulk_insert(table,
        [
            {'name': 'Программирование'},
            {'name': 'Математика'},
            {'name': 'Языкознание'},
        ]
    )